// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Torneo.API.Migrations
{
    [DbContext(typeof(TorneoAPIContext))]
    partial class TorneoAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Torneo.Modelos.Equipos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("Torneo.Modelos.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<int>("Goles")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PartidosSuspendido")
                        .HasColumnType("integer");

                    b.Property<int>("TarjetasAmarillas")
                        .HasColumnType("integer");

                    b.Property<int>("TarjetasRojas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.ToTable("Jugador");
                });

            modelBuilder.Entity("Torneo.Modelos.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoLocalId")
                        .HasColumnType("integer");

                    b.Property<int>("EquiposId")
                        .HasColumnType("integer");

                    b.Property<int>("GC")
                        .HasColumnType("integer");

                    b.Property<int>("GF")
                        .HasColumnType("integer");

                    b.Property<int>("TorneoId")
                        .HasColumnType("integer");

                    b.Property<int>("diferencia")
                        .HasColumnType("integer");

                    b.Property<int>("partidosJugados")
                        .HasColumnType("integer");

                    b.Property<int>("puntos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TorneoId");

                    b.ToTable("Partido");
                });

            modelBuilder.Entity("Torneo.Modelos.TipoTorneo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoTorneo");
                });

            modelBuilder.Entity("Torneo.Modelos.Torneo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoId")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoTorneoId")
                        .HasColumnType("integer");

                    b.Property<string>("fechaFin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fechaInicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("TipoTorneoId");

                    b.ToTable("Torneo");
                });

            modelBuilder.Entity("Torneo.Modelos.TorneoEquipo", b =>
                {
                    b.Property<int>("TorneoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TorneoId"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<int>("GolesContra")
                        .HasColumnType("integer");

                    b.Property<int>("GolesFavor")
                        .HasColumnType("integer");

                    b.Property<int>("PartidosJugados")
                        .HasColumnType("integer");

                    b.Property<int>("Puntos")
                        .HasColumnType("integer");

                    b.Property<int>("TorneoID")
                        .HasColumnType("integer");

                    b.HasKey("TorneoId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("TorneoID");

                    b.ToTable("TorneoEquipo");
                });

            modelBuilder.Entity("Torneo.Modelos.Jugador", b =>
                {
                    b.HasOne("Torneo.Modelos.Equipos", "Equipo")
                        .WithMany("Jugador")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("Torneo.Modelos.Partido", b =>
                {
                    b.HasOne("Torneo.Modelos.Torneo", null)
                        .WithMany("Partido")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Torneo.Modelos.Torneo", b =>
                {
                    b.HasOne("Torneo.Modelos.TipoTorneo", "TipoTorneo")
                        .WithMany()
                        .HasForeignKey("TipoTorneoId");

                    b.Navigation("TipoTorneo");
                });

            modelBuilder.Entity("Torneo.Modelos.TorneoEquipo", b =>
                {
                    b.HasOne("Torneo.Modelos.Equipos", "Equipo")
                        .WithMany("Torneo")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torneo.Modelos.Torneo", "Torneo")
                        .WithMany("Equipos")
                        .HasForeignKey("TorneoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("Torneo.Modelos.Equipos", b =>
                {
                    b.Navigation("Jugador");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("Torneo.Modelos.Torneo", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("Partido");
                });
#pragma warning restore 612, 618
        }
    }
}
